#include <stdio.h>

int main() {
    FILE *fp = fopen("tree_depth_calculator.html", "w");
    if (fp == NULL) {
        printf("Error opening file for writing.\n");
        return 1;
    }

    const char *html_content =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>Tree Depth Calculator</title>\n"
"    <style>\n"
"        body {\n"
"            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n"
"            background: linear-gradient(135deg, #74ebd5 0%, #ACB6E5 100%);\n"
"            margin: 0;\n"
"            padding: 0;\n"
"            display: flex;\n"
"            flex-direction: column;\n"
"            align-items: center;\n"
"            justify-content: flex-start;\n"
"            min-height: 100vh;\n"
"            color: #222;\n"
"        }\n"
"        header {\n"
"            margin: 40px 0 20px 0;\n"
"            text-align: center;\n"
"            font-size: 2.5rem;\n"
"            font-weight: bold;\n"
"            color: #1a1a1a;\n"
"        }\n"
"        main {\n"
"            background: white;\n"
"            border-radius: 10px;\n"
"            padding: 30px;\n"
"            box-shadow: 0 8px 20px rgba(0,0,0,0.15);\n"
"            max-width: 600px;\n"
"            width: 90%;\n"
"        }\n"
"        label {\n"
"            font-size: 1.2rem;\n"
"            margin-bottom: 10px;\n"
"            display: block;\n"
"        }\n"
"        textarea {\n"
"            width: 100%;\n"
"            height: 120px;\n"
"            font-size: 1rem;\n"
"            padding: 10px;\n"
"            border-radius: 6px;\n"
"            border: 1px solid #ccc;\n"
"            resize: vertical;\n"
"            font-family: monospace;\n"
"        }\n"
"        button {\n"
"            margin-top: 20px;\n"
"            padding: 12px 24px;\n"
"            font-size: 1.1rem;\n"
"            background: #4a90e2;\n"
"            color: white;\n"
"            border: none;\n"
"            border-radius: 8px;\n"
"            cursor: pointer;\n"
"        }\n"
"        button:hover {\n"
"            background: #357ABD;\n"
"        }\n"
"        .result {\n"
"            margin-top: 20px;\n"
"            font-size: 1.4rem;\n"
"            font-weight: 600;\n"
"            color: #333;\n"
"            text-align: center;\n"
"        }\n"
"        footer {\n"
"            margin: 40px 0;\n"
"            color: #555;\n"
"        }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <header>Tree Depth Calculator</header>\n"
"    <main>\n"
"        <label for=\"treeInput\">Enter tree structure (e.g., (1(2)(3(4)))(5)):</label>\n"
"        <textarea id=\"treeInput\" placeholder=\"Enter tree structure here...\"></textarea>\n"
"        <button onclick=\"calculateDepth()\">Calculate Depth</button>\n"
"        <div class=\"result\" id=\"result\"></div>\n"
"    </main>\n"
"    <footer>&copy; 2025 Tree Tools</footer>\n"
"\n"
"<script>\n"
"function calculateDepth() {\n"
"    const input = document.getElementById('treeInput').value;\n"
"    let index = 0;\n"
"    function parse() {\n"
"        if (index >= input.length || input[index] !== '(') return 0;\n"
"        index++; // skip '('\n"
"        let maxDepth = 0;\n"
"        while (index < input.length && input[index] !== ')') {\n"
"            if (input[index] === '(') {\n"
"                const childDepth = parse();\n"
"                if (childDepth > maxDepth) maxDepth = childDepth;\n"
"            } else {\n"
"                index++;\n"
"            }\n"
"        }\n"
"        index++; // skip ')'\n"
"        return maxDepth + 1;\n"
"    }\n"
"    index = 0;\n"
"    const depth = parse();\n"
"    document.getElementById('result').textContent = 'Depth: ' + depth;\n"
"}\n"
"</script>\n"
"</body>\n"
"</html>\n";

    fprintf(fp, "%s", html_content);
    fclose(fp);

    printf("tree_depth_calculator.html generated successfully.\n");
    return 0;
}
